name: CI

on:
  push:
    branches:
      - production
      - dev
    tags:
      - 1.*
  pull_request:
    branches: [ production ]

  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install composer packages
        run: |
          php -v
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

      - name: Compress composer folder
        run: tar -czvf composer.tgz vendor/

      - name: Upload composer assets
        uses: actions/upload-artifact@v2
        with:
          name: composer
          path: composer.tgz
          retention-days: 3

  phpcs:
    runs-on: ubuntu-latest
    needs: [composer]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download composer artifacts
        uses: actions/download-artifact@v2
        with:
          name: composer

      - name: Unpack composer artifacts
        run: |
          tar xvfz composer.tgz

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Execute PHP_CodeSniffer
        run: |
          php -v
          composer php-lint
          composer phpcs
